import type { Certification } from "@/content/types";

const certification: Certification = {
  slug: "gcp-generative-ai-leader",
  providerId: "gcp",
  code: "Generative AI Leader",
  name: "Google Cloud Generative AI Leader",
  level: "Fondamentaux",
  tagline: "La certification Google Cloud pensée pour piloter l'IA générative sans écrire une ligne de code.",
  description:
    "La certification Generative AI Leader valide la compréhension des concepts, des outils et des usages métier de l'IA générative sur Google Cloud. Elle vise les décideurs, chefs de produit, consultants et managers qui doivent cadrer des projets d'IA générative sans forcément coder eux-mêmes. Elle sert de repère commun entre équipes techniques et non techniques sur le vocabulaire, les capacités de la plateforme Vertex AI et les bonnes pratiques d'IA responsable.",
  officialUrl: "https://cloud.google.com/learn/certification/generative-ai-leader",
  format: {
    questionCount: 50,
    durationMinutes: 90,
    passingScore: "Non communiqué publiquement par Google (réussite/échec uniquement)",
    price: "Tarif indicatif ~99 USD (vérifier le tarif en vigueur sur le site Google Cloud, la certification a été gratuite lors de son lancement)",
    deliveryMode: "Examen en ligne surveillé à distance",
    isOfficialCertification: true,
  },
  domains: [
    {
      id: "fondamentaux",
      title: "Fondamentaux de l'IA générative",
      weightPercent: 25,
      summary:
        "Les notions de base pour comprendre ce qu'est un modèle de fondation, comment il est entraîné et utilisé, et ce qui distingue l'IA générative de l'IA prédictive classique.",
    },
    {
      id: "offre-google-cloud",
      title: "L'offre Google Cloud pour l'IA générative",
      weightPercent: 30,
      summary:
        "La plateforme Vertex AI, le Model Garden, la famille de modèles Gemini, Imagen, et les briques permettant de construire des agents et des applications d'IA générative.",
    },
    {
      id: "techniques-amelioration",
      title: "Techniques pour améliorer les résultats des modèles",
      weightPercent: 25,
      summary:
        "Les leviers concrets pour obtenir de meilleures réponses d'un modèle : prompt engineering, ancrage des réponses (grounding), RAG et fine-tuning.",
    },
    {
      id: "strategie-business",
      title: "Stratégie business et IA responsable",
      weightPercent: 20,
      summary:
        "Le cadrage des cas d'usage métier, l'évaluation du retour sur investissement, la gouvernance des projets d'IA et les principes d'IA responsable défendus par Google.",
    },
  ],
  modules: [
    {
      slug: "comprendre-ia-generative",
      domainId: "fondamentaux",
      title: "Comprendre l'IA générative et les modèles de fondation",
      readMinutes: 9,
      summary:
        "Ce module pose le vocabulaire de base de l'IA générative : modèles de fondation, grands modèles de langage, entraînement, inférence et prompting, pour donner à un décideur les repères nécessaires avant d'aborder l'offre Google Cloud.",
      keyPoints: [
        "L'IA générative produit du contenu nouveau (texte, image, audio, code) plutôt que de simplement classer ou prédire une valeur.",
        "Un modèle de fondation est entraîné sur de très grands volumes de données puis adapté à de nombreuses tâches différentes.",
        "L'entraînement et l'inférence sont deux phases distinctes : la première façonne le modèle, la seconde l'utilise pour produire une réponse.",
        "Un prompt est l'instruction envoyée au modèle ; sa qualité influence directement la qualité de la réponse.",
        "Les grands modèles de langage (LLM) sont un cas particulier de modèle de fondation spécialisé dans le texte et le langage.",
      ],
      sections: [
        {
          heading: "De l'IA prédictive à l'IA générative",
          body: "L'IA prédictive classique apprend à reconnaître des motifs dans des données existantes pour classer, scorer ou prévoir : détecter une fraude, prédire une résiliation, recommander un produit déjà catalogué. L'IA générative va plus loin : elle apprend la structure profonde du langage, de l'image ou du son pour produire du contenu inédit. Un modèle de génération de texte ne choisit pas une réponse parmi une liste fermée, il construit une séquence de mots nouvelle, cohérente avec le contexte donné. Cette distinction est centrale pour un décideur, car elle change la nature des cas d'usage possibles : rédaction, synthèse, génération de code, création visuelle, dialogue conversationnel, là où l'IA prédictive reste cantonnée à des tâches de classification ou de scoring.",
        },
        {
          heading: "Les modèles de fondation",
          body: "Un modèle de fondation est un modèle entraîné sur un très grand volume de données diverses (texte, code, images selon les cas), avec suffisamment de paramètres pour capturer des régularités générales du langage et du raisonnement. Sa force est la polyvalence : le même modèle de base peut ensuite être adapté, par prompting ou par fine-tuning, à des tâches très variées comme la synthèse de documents, la génération de code ou la classification de sentiment, sans devoir entraîner un modèle spécifique pour chaque tâche. Les grands modèles de langage (LLM) constituent la famille de modèles de fondation la plus connue, spécialisée dans la compréhension et la génération de texte. Google propose sa propre famille de modèles de fondation sous le nom Gemini, multimodale dès sa conception.",
        },
        {
          heading: "Entraînement et inférence",
          body: "Deux phases distinctes structurent le cycle de vie d'un modèle. L'entraînement consiste à exposer le modèle à d'immenses volumes de données pour ajuster ses paramètres internes, un processus coûteux en calcul qui se déroule une fois, ou périodiquement pour les mises à jour du modèle. L'inférence est l'utilisation du modèle déjà entraîné pour produire une réponse à partir d'une nouvelle entrée : c'est ce qui se passe chaque fois qu'un utilisateur envoie un prompt et reçoit une réponse. Pour un décideur, cette distinction éclaire la structure des coûts : l'entraînement d'un modèle de fondation depuis zéro est réservé à quelques acteurs disposant d'infrastructures massives, alors que l'inférence, elle, est accessible à toute organisation via une API comme celle de Vertex AI.",
        },
        {
          heading: "Le prompting comme premier levier",
          body: "Le prompt est l'instruction textuelle, ou multimodale, envoyée au modèle pour obtenir une réponse. Sans changer un seul paramètre du modèle, la formulation du prompt influence fortement la qualité, la précision et le format de la réponse obtenue. C'est le levier le plus rapide et le moins coûteux pour améliorer un résultat, avant d'envisager des techniques plus avancées comme le RAG ou le fine-tuning, abordées dans un autre module. Un bon prompt précise le contexte, le rôle attendu du modèle, le format de sortie souhaité et, si besoin, des exemples de réponses correctes.",
        },
        {
          heading: "Multimodalité et limites actuelles",
          body: "Les modèles récents comme Gemini sont multimodaux : ils traitent et génèrent plusieurs types de contenus (texte, image, audio, vidéo, code) au sein d'un même modèle. Cela ouvre des cas d'usage combinant plusieurs formats, par exemple analyser une image et répondre à une question textuelle à son sujet. Ces modèles restent toutefois sujets à des limites connues : ils peuvent produire des réponses incorrectes avec assurance, un phénomène appelé hallucination, et leurs connaissances sont bornées par leurs données d'entraînement à une date donnée. Ces limites justifient les techniques d'ancrage et de vérification présentées plus loin dans la formation.",
        },
      ],
    },
    {
      slug: "vertex-ai-et-offre-google-cloud",
      domainId: "offre-google-cloud",
      title: "Vertex AI, Model Garden, Gemini et Imagen",
      readMinutes: 11,
      summary:
        "Ce module présente l'écosystème Google Cloud pour l'IA générative : la plateforme unifiée Vertex AI, le catalogue de modèles Model Garden, la famille Gemini, le générateur d'images Imagen et les briques pour construire des agents.",
      keyPoints: [
        "Vertex AI est la plateforme unifiée de Google Cloud pour entraîner, adapter, déployer et gouverner des modèles de machine learning et d'IA générative.",
        "Model Garden regroupe des modèles de fondation de Google, de partenaires et open source accessibles depuis une interface unique.",
        "Gemini est la famille de modèles multimodaux de Google, déclinée en plusieurs tailles selon le compromis coût/performance recherché.",
        "Imagen est le modèle Google Cloud spécialisé dans la génération et l'édition d'images à partir de texte.",
        "Vertex AI Search et les frameworks d'agents permettent de construire des applications de recherche et des agents ancrés dans les données de l'entreprise.",
      ],
      sections: [
        {
          heading: "Vertex AI, la plateforme unifiée",
          body: "Vertex AI est la plateforme de machine learning et d'IA générative de Google Cloud. Elle centralise l'ensemble du cycle de vie d'un projet d'IA : accès aux modèles, adaptation par prompt ou par fine-tuning, évaluation, déploiement en production et supervision. Pour une organisation, l'intérêt d'une plateforme unifiée est de réduire la fragmentation des outils entre les équipes data science, les équipes produit et les équipes d'exploitation, et de bénéficier des mêmes standards de sécurité et de gouvernance sur tous les projets d'IA. Vertex AI s'appuie sur l'infrastructure Google Cloud existante, ce qui facilite l'intégration avec les données déjà stockées dans BigQuery, Cloud Storage ou d'autres services du cloud.",
        },
        {
          heading: "Model Garden, le catalogue de modèles",
          body: "Model Garden est le catalogue de modèles disponibles dans Vertex AI. Il regroupe les modèles propriétaires de Google comme Gemini et Imagen, des modèles de partenaires, et des modèles open source populaires. Ce catalogue permet à une organisation de comparer plusieurs modèles sur un même cas d'usage, de choisir celui qui offre le meilleur compromis entre coût, latence et qualité de réponse, et d'éviter de dépendre d'un seul fournisseur de modèle. Pour un décideur, Model Garden matérialise un principe important : le choix du modèle est une décision produit, pas seulement une décision technique, qui doit tenir compte du budget, de la sensibilité des données et des exigences de performance.",
        },
        {
          heading: "La famille de modèles Gemini",
          body: "Gemini est la famille de modèles de fondation multimodaux développée par Google. Elle est déclinée en plusieurs variantes qui répondent à des besoins différents : des versions plus légères et rapides pour des tâches simples à grande échelle, et des versions plus puissantes pour du raisonnement complexe ou des tâches multimodales exigeantes. Cette déclinaison permet d'ajuster le coût d'inférence à la complexité réelle de la tâche, plutôt que d'utiliser systématiquement le modèle le plus puissant et le plus coûteux. Gemini est accessible via Vertex AI, mais aussi via d'autres points d'entrée grand public, ce qui en fait le socle des expériences génératives de Google, y compris son assistant conversationnel.",
        },
        {
          heading: "Imagen et la génération d'images",
          body: "Imagen est le modèle Google Cloud dédié à la génération et à l'édition d'images à partir d'instructions textuelles. Il permet de créer des visuels originaux, de modifier des images existantes ou d'en étendre le cadrage, avec des garde-fous intégrés pour limiter la génération de contenus problématiques comme des images de personnes réelles sans consentement. Dans un contexte d'entreprise, Imagen s'utilise typiquement pour accélérer la production de visuels marketing, de maquettes ou de variantes créatives, sous supervision humaine avant toute publication.",
        },
        {
          heading: "Agents, Vertex AI Search et applications d'entreprise",
          body: "Au-delà des modèles bruts, Google Cloud propose des briques pour construire des applications complètes. Vertex AI Search permet de créer des expériences de recherche et de question-réponse ancrées dans les documents propres à une entreprise, sans avoir à réentraîner un modèle. Les frameworks d'agents de Google Cloud permettent d'assembler un modèle, des outils externes (appels d'API, bases de données, moteurs de recherche) et une logique de décision pour automatiser des tâches à plusieurs étapes, par exemple traiter une demande client de bout en bout. Ces briques se combinent avec Gemini et Model Garden pour constituer des applications d'IA générative complètes, pensées pour l'usage professionnel plutôt que pour l'expérimentation isolée.",
        },
      ],
    },
    {
      slug: "ameliorer-resultats-modeles",
      domainId: "techniques-amelioration",
      title: "Prompt engineering, grounding, RAG et fine-tuning",
      readMinutes: 10,
      summary:
        "Ce module détaille les quatre grandes techniques pour améliorer les réponses d'un modèle d'IA générative, de la plus simple et la moins coûteuse à la plus exigeante en données et en calcul.",
      keyPoints: [
        "Le prompt engineering optimise la formulation de l'instruction sans modifier le modèle ni ajouter de données externes.",
        "Le grounding ancre les réponses du modèle dans des sources vérifiables, comme la recherche Google ou des documents d'entreprise.",
        "Le RAG (retrieval-augmented generation) va chercher des informations pertinentes dans une base documentaire avant de générer la réponse.",
        "Le fine-tuning ajuste les paramètres internes du modèle à partir d'exemples spécifiques à un domaine ou une tâche.",
        "Le choix de la technique dépend du volume de données disponible, du budget et du besoin de traçabilité des réponses.",
      ],
      sections: [
        {
          heading: "Le prompt engineering, premier réflexe",
          body: "Le prompt engineering consiste à structurer et affiner l'instruction envoyée au modèle pour obtenir une réponse plus précise, sans toucher au modèle lui-même. Les techniques courantes incluent la définition claire d'un rôle ou d'un persona pour le modèle, la fourniture d'exemples de réponses attendues, dite few-shot prompting, la décomposition d'un problème complexe en étapes explicites, et la précision du format de sortie souhaité. C'est la technique la plus rapide à mettre en œuvre et la moins coûteuse, ce qui en fait le point de départ recommandé avant d'envisager des approches plus lourdes comme le RAG ou le fine-tuning.",
        },
        {
          heading: "Le grounding, ancrer les réponses dans des faits",
          body: "Le grounding, ou ancrage, consiste à connecter les réponses du modèle à des sources d'information vérifiables plutôt que de le laisser générer une réponse uniquement à partir de ses connaissances internes, potentiellement obsolètes ou incorrectes. Sur Google Cloud, le grounding peut s'appuyer sur la recherche Google pour des informations publiques et récentes, ou sur des documents internes à l'entreprise via Vertex AI Search. L'intérêt principal du grounding est de réduire les hallucinations et de permettre de citer les sources utilisées, un point souvent décisif dans des contextes réglementés ou à forte exigence de fiabilité.",
        },
        {
          heading: "Le RAG, retrieval-augmented generation",
          body: "Le RAG est une architecture qui combine un système de recherche documentaire et un modèle génératif. Avant de répondre, le système recherche dans une base de documents (contrats, manuels, bases de connaissance internes) les passages les plus pertinents par rapport à la question posée, puis les transmet au modèle comme contexte pour construire sa réponse. Cette approche permet d'exploiter des données propriétaires ou très récentes sans avoir à réentraîner le modèle, et elle limite les hallucinations puisque le modèle s'appuie sur des extraits réels plutôt que sur sa seule mémoire. Le RAG demande en revanche de mettre en place une infrastructure de recherche et d'indexation, ce qui représente un effort d'ingénierie supérieur au simple prompt engineering.",
        },
        {
          heading: "Le fine-tuning, adapter le modèle lui-même",
          body: "Le fine-tuning consiste à poursuivre l'entraînement d'un modèle de fondation sur un jeu de données spécifique à une tâche ou à un domaine, ce qui modifie ses paramètres internes. Cette technique convient quand un cas d'usage exige un style de réponse très particulier, un vocabulaire métier spécialisé, ou une tâche répétée à très grande échelle où un léger gain de précision par requête se traduit en économies substantielles. Le fine-tuning demande davantage de données étiquetées, de budget de calcul et d'expertise que le prompt engineering ou le RAG, et il doit être réévalué à chaque nouvelle version du modèle de base. C'est généralement la dernière option envisagée, après avoir épuisé les gains possibles du prompting et du RAG.",
        },
        {
          heading: "Choisir la bonne combinaison de techniques",
          body: "Dans la pratique, ces techniques ne s'excluent pas : une application d'entreprise combine souvent un prompt bien conçu, un ancrage sur une base documentaire via RAG, et parfois un fine-tuning léger pour calibrer le ton des réponses. Le choix dépend de critères concrets : le volume et la fraîcheur des données disponibles, le budget alloué au projet, l'exigence de traçabilité des réponses, et la criticité des erreurs possibles. Un décideur doit être capable d'arbitrer entre ces options avec son équipe technique plutôt que d'imposer une solution a priori, car la complexité et le coût augmentent fortement du simple prompting jusqu'au fine-tuning.",
        },
      ],
    },
    {
      slug: "strategie-ia-responsable",
      domainId: "strategie-business",
      title: "Cadrer un projet d'IA générative et l'IA responsable chez Google",
      readMinutes: 9,
      summary:
        "Ce module couvre l'identification et l'évaluation des cas d'usage métier, les questions de retour sur investissement et de gouvernance, ainsi que les principes d'IA responsable défendus par Google.",
      keyPoints: [
        "Un projet d'IA générative se cadre d'abord par le problème métier à résoudre, pas par la technologie disponible.",
        "L'évaluation du retour sur investissement doit tenir compte des coûts d'inférence récurrents, pas seulement du coût de mise en place initiale.",
        "La gouvernance d'un projet d'IA générative couvre la qualité des données, la sécurité, les accès et la conformité réglementaire.",
        "Google structure son IA responsable autour de principes publics couvrant le bénéfice social, la sécurité, l'équité, la confidentialité et la responsabilité humaine.",
        "Un déploiement responsable inclut des tests de biais, une supervision humaine et une communication claire aux utilisateurs finaux sur l'usage de l'IA.",
      ],
      sections: [
        {
          heading: "Partir du cas d'usage, pas de la technologie",
          body: "Un projet d'IA générative réussi part toujours d'un problème métier précis : réduire le temps de traitement d'une demande client, accélérer la rédaction de documents internes, améliorer la recherche dans une base de connaissances. L'erreur fréquente consiste à choisir la technologie avant d'avoir clarifié le problème, ce qui conduit à des projets techniquement impressionnants mais sans valeur métier mesurable. Un décideur doit être capable de formuler le cas d'usage en termes de métrique business claire : temps gagné, taux de satisfaction, coût évité, avant de solliciter les équipes techniques pour évaluer la faisabilité.",
        },
        {
          heading: "Évaluer le retour sur investissement",
          body: "Le calcul du retour sur investissement d'un projet d'IA générative diffère de celui d'un projet logiciel classique. Aux coûts de développement initial s'ajoutent des coûts récurrents liés à l'inférence, c'est-à-dire au nombre de requêtes envoyées au modèle en production, qui varient selon le volume d'usage et la taille du modèle choisi. Un projet qui semble rentable en phase pilote sur un petit volume de requêtes peut voir son coût grimper significativement une fois déployé à l'échelle de toute l'organisation. Il est donc essentiel d'estimer le coût d'inférence à l'échelle cible dès la phase de cadrage, et de comparer plusieurs tailles de modèles pour trouver le meilleur compromis coût-performance pour le cas d'usage visé.",
        },
        {
          heading: "Gouvernance et conduite du changement",
          body: "La gouvernance d'un projet d'IA générative couvre plusieurs dimensions : la qualité et la provenance des données utilisées, en particulier pour le RAG et le fine-tuning, la gestion des accès et de la sécurité autour des modèles et des données sensibles, et la conformité aux réglementations applicables au secteur d'activité. Au-delà de l'aspect technique, la conduite du changement est déterminante : les équipes concernées doivent comprendre ce que l'outil fait, ses limites, et dans quels cas une validation humaine reste nécessaire. Un projet d'IA générative sans adhésion des utilisateurs finaux échoue souvent, même quand la technologie fonctionne correctement.",
        },
        {
          heading: "Les principes d'IA responsable de Google",
          body: "Google a publié des principes d'IA responsable qui encadrent le développement et le déploiement de ses modèles. Ces principes demandent qu'une application d'IA soit socialement bénéfique, évite de créer ou renforcer des biais injustes, soit conçue et testée pour la sécurité, rende des comptes aux personnes concernées, intègre des principes de confidentialité dès la conception, maintienne des standards scientifiques élevés, et reste limitée à des usages qui respectent ces principes, avec des domaines d'application explicitement exclus comme les armes ou la surveillance de masse. Pour une organisation utilisatrice de Vertex AI, ces principes ne sont pas qu'une déclaration d'intention : ils se traduisent par des outils concrets d'évaluation des biais, de filtrage de contenu et de documentation des modèles fournis par Google Cloud.",
        },
        {
          heading: "Mettre en pratique une IA responsable au quotidien",
          body: "Concrètement, un déploiement responsable d'IA générative en entreprise comprend plusieurs pratiques : tester le modèle sur des cas limites et des populations diverses pour détecter des biais avant la mise en production, maintenir une supervision humaine sur les décisions à fort impact plutôt que de tout automatiser, informer clairement les utilisateurs finaux quand ils interagissent avec une IA générative plutôt qu'avec un humain, et mettre en place des mécanismes de retour pour corriger les erreurs constatées après déploiement. Ces pratiques ne ralentissent pas un projet, elles réduisent le risque de devoir le retirer en urgence après un incident réputationnel ou réglementaire.",
        },
      ],
    },
  ],
  glossary: [
    {
      term: "Modèle de fondation",
      definition: "Modèle entraîné sur un très grand volume de données diverses, conçu pour être adapté ensuite à de nombreuses tâches différentes par prompting ou fine-tuning.",
      domainId: "fondamentaux",
    },
    {
      term: "Grand modèle de langage (LLM)",
      definition: "Modèle de fondation spécialisé dans la compréhension et la génération de texte, entraîné sur de vastes corpus linguistiques.",
      domainId: "fondamentaux",
    },
    {
      term: "Inférence",
      definition: "Phase d'utilisation d'un modèle déjà entraîné pour produire une réponse à partir d'une nouvelle entrée, par opposition à l'entraînement.",
      domainId: "fondamentaux",
    },
    {
      term: "Entraînement",
      definition: "Processus par lequel un modèle ajuste ses paramètres internes à partir de grands volumes de données, avant sa mise en service.",
      domainId: "fondamentaux",
    },
    {
      term: "Prompt",
      definition: "Instruction textuelle ou multimodale envoyée à un modèle d'IA générative pour obtenir une réponse.",
      domainId: "fondamentaux",
    },
    {
      term: "Hallucination",
      definition: "Réponse générée par un modèle qui semble plausible et assurée mais qui est factuellement incorrecte ou inventée.",
      domainId: "fondamentaux",
    },
    {
      term: "Multimodalité",
      definition: "Capacité d'un modèle à traiter et générer simultanément plusieurs types de contenus, comme du texte, des images, de l'audio ou de la vidéo.",
      domainId: "fondamentaux",
    },
    {
      term: "Vertex AI",
      definition: "Plateforme unifiée de Google Cloud pour entraîner, adapter, déployer et gouverner des modèles de machine learning et d'IA générative.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Model Garden",
      definition: "Catalogue de modèles disponibles dans Vertex AI, regroupant les modèles Google, des modèles partenaires et des modèles open source.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Gemini",
      definition: "Famille de modèles de fondation multimodaux développée par Google, déclinée en plusieurs tailles selon le compromis coût-performance recherché.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Imagen",
      definition: "Modèle Google Cloud dédié à la génération et à l'édition d'images à partir d'instructions textuelles.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Vertex AI Search",
      definition: "Service Google Cloud permettant de créer des expériences de recherche et de question-réponse ancrées dans les documents propres à une entreprise.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Agent",
      definition: "Système combinant un modèle génératif, des outils externes et une logique de décision pour automatiser une tâche à plusieurs étapes de façon autonome.",
      domainId: "offre-google-cloud",
    },
    {
      term: "API",
      definition: "Interface de programmation permettant à une application d'envoyer des requêtes à un modèle hébergé sur Vertex AI et de recevoir ses réponses.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Prompt engineering",
      definition: "Pratique consistant à formuler et structurer un prompt de façon à obtenir la meilleure réponse possible d'un modèle, sans modifier le modèle lui-même.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Few-shot prompting",
      definition: "Technique de prompt engineering consistant à fournir quelques exemples de réponses attendues dans le prompt pour guider le modèle.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Grounding (ancrage)",
      definition: "Technique consistant à connecter les réponses d'un modèle à des sources d'information vérifiables, comme la recherche Google ou des documents d'entreprise, pour réduire les hallucinations.",
      domainId: "techniques-amelioration",
    },
    {
      term: "RAG (retrieval-augmented generation)",
      definition: "Architecture combinant une recherche documentaire et un modèle génératif, où les passages les plus pertinents d'une base de documents sont transmis au modèle comme contexte avant qu'il ne réponde.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Fine-tuning",
      definition: "Poursuite de l'entraînement d'un modèle de fondation sur un jeu de données spécifique à une tâche ou un domaine, ce qui modifie ses paramètres internes.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Embedding",
      definition: "Représentation numérique d'un texte, d'une image ou d'un autre contenu sous forme de vecteur, utilisée notamment pour la recherche de similarité dans un système RAG.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Retour sur investissement (ROI)",
      definition: "Mesure de la valeur créée par un projet d'IA générative rapportée à son coût total, incluant les coûts récurrents d'inférence en production.",
      domainId: "strategie-business",
    },
    {
      term: "Gouvernance de l'IA",
      definition: "Ensemble des pratiques encadrant la qualité des données, la sécurité, les accès et la conformité réglementaire d'un projet d'IA générative.",
      domainId: "strategie-business",
    },
    {
      term: "IA responsable",
      definition: "Approche du développement et du déploiement de l'IA qui vise à limiter les biais, protéger la confidentialité, garantir la sécurité et rendre des comptes sur les décisions prises par un système.",
      domainId: "strategie-business",
    },
    {
      term: "Biais algorithmique",
      definition: "Écart systématique dans les résultats d'un modèle qui désavantage injustement certains groupes ou certaines catégories de données.",
      domainId: "strategie-business",
    },
    {
      term: "Supervision humaine (human in the loop)",
      definition: "Pratique consistant à maintenir une validation ou une intervention humaine sur les décisions à fort impact prises avec l'aide d'un système d'IA générative.",
      domainId: "strategie-business",
    },
  ],
  quizBank: [
    {
      id: "gcp-genai-q01",
      domainId: "fondamentaux",
      difficulty: "facile",
      question: "Qu'est-ce qui distingue principalement l'IA générative de l'IA prédictive classique ?",
      options: [
        "L'IA générative produit du contenu nouveau alors que l'IA prédictive classe ou prévoit à partir de catégories existantes",
        "L'IA générative fonctionne uniquement sur des données numériques structurées",
        "L'IA prédictive est plus récente que l'IA générative",
        "L'IA générative n'a besoin d'aucune donnée d'entraînement",
      ],
      correctIndex: 0,
      explanation: "L'IA générative crée du contenu inédit (texte, image, code) tandis que l'IA prédictive classique classe, score ou prévoit à partir de catégories ou de valeurs déjà connues.",
    },
    {
      id: "gcp-genai-q02",
      domainId: "fondamentaux",
      difficulty: "facile",
      question: "Un chef de produit veut comprendre pourquoi son équipe technique parle de deux phases distinctes, l'entraînement et l'inférence. Que représente l'inférence ?",
      options: [
        "La phase où le modèle ajuste ses paramètres sur de grands volumes de données",
        "La phase d'utilisation du modèle déjà entraîné pour produire une réponse à une nouvelle requête",
        "La phase de collecte des données avant tout entraînement",
        "La phase de suppression d'un modèle obsolète",
      ],
      correctIndex: 1,
      explanation: "L'inférence est l'utilisation du modèle déjà entraîné pour répondre à une nouvelle entrée. L'entraînement, lui, ajuste les paramètres du modèle à partir des données.",
    },
    {
      id: "gcp-genai-q03",
      domainId: "fondamentaux",
      difficulty: "moyen",
      question: "Une équipe constate qu'un modèle génère avec assurance une réponse factuellement fausse sur un sujet précis. Comment nomme-t-on ce phénomène ?",
      options: [
        "Un biais algorithmique",
        "Une hallucination",
        "Un sur-apprentissage",
        "Une régression de performance",
      ],
      correctIndex: 1,
      explanation: "Une hallucination désigne une réponse générée par le modèle qui semble plausible et assurée mais qui est en réalité incorrecte ou inventée.",
    },
    {
      id: "gcp-genai-q04",
      domainId: "fondamentaux",
      difficulty: "moyen",
      question: "Qu'est-ce qu'un modèle de fondation ?",
      options: [
        "Un modèle entraîné pour une seule tâche très spécifique, comme la détection de spam",
        "Un modèle entraîné sur de vastes données diverses et conçu pour être adapté à de nombreuses tâches",
        "Un modèle qui ne peut traiter que du texte, jamais d'images",
        "Un modèle open source par opposition aux modèles propriétaires",
      ],
      correctIndex: 1,
      explanation: "Un modèle de fondation est entraîné sur de grands volumes de données diverses, ce qui lui permet d'être ensuite adapté à de multiples tâches par prompting ou fine-tuning.",
    },
    {
      id: "gcp-genai-q05",
      domainId: "fondamentaux",
      difficulty: "facile",
      question: "Qu'appelle-t-on la multimodalité d'un modèle comme Gemini ?",
      options: [
        "Sa capacité à fonctionner sur plusieurs clouds en même temps",
        "Sa capacité à traiter et générer plusieurs types de contenus, comme le texte, l'image et l'audio",
        "Sa capacité à être utilisé par plusieurs utilisateurs simultanément",
        "Sa capacité à changer automatiquement de fournisseur cloud",
      ],
      correctIndex: 1,
      explanation: "La multimodalité désigne la capacité d'un modèle à traiter et produire simultanément plusieurs types de contenus : texte, image, audio, vidéo.",
    },
    {
      id: "gcp-genai-q06",
      domainId: "fondamentaux",
      difficulty: "difficile",
      question: "Une startup veut entraîner son propre modèle de fondation depuis zéro pour un cas d'usage de service client. Quel constat un Generative AI Leader devrait-il faire ?",
      options: [
        "C'est la meilleure approche recommandée par défaut pour tout projet d'IA générative",
        "L'entraînement d'un modèle de fondation depuis zéro demande des ressources considérables, alors que l'adaptation d'un modèle existant via prompting, RAG ou fine-tuning est généralement suffisante et bien moins coûteuse",
        "C'est impossible techniquement en dehors de Google",
        "Cela ne change rien au coût par rapport à l'utilisation d'un modèle existant via une API",
      ],
      correctIndex: 1,
      explanation: "Entraîner un modèle de fondation depuis zéro exige une infrastructure et des volumes de données considérables. La grande majorité des cas d'usage d'entreprise s'appuient plutôt sur l'adaptation d'un modèle existant.",
    },
    {
      id: "gcp-genai-q07",
      domainId: "fondamentaux",
      difficulty: "moyen",
      question: "Pourquoi un LLM (grand modèle de langage) est-il considéré comme un cas particulier de modèle de fondation ?",
      options: [
        "Parce qu'il est toujours plus petit qu'un modèle de fondation",
        "Parce qu'il s'agit d'un modèle de fondation spécialisé dans la compréhension et la génération de texte",
        "Parce qu'il ne peut pas être utilisé via une API",
        "Parce qu'il est entraîné sans aucune donnée textuelle",
      ],
      correctIndex: 1,
      explanation: "Un LLM est un modèle de fondation dont la spécialité porte sur le langage : il est entraîné sur de vastes corpus textuels pour comprendre et générer du texte.",
    },
    {
      id: "gcp-genai-q08",
      domainId: "fondamentaux",
      difficulty: "facile",
      question: "Quel élément influence directement la qualité de la réponse d'un modèle sans nécessiter de modifier le modèle lui-même ?",
      options: [
        "Le fine-tuning",
        "Le prompt envoyé au modèle",
        "Le réentraînement complet du modèle",
        "Le changement de fournisseur cloud",
      ],
      correctIndex: 1,
      explanation: "Le prompt, c'est-à-dire l'instruction envoyée au modèle, influence directement la qualité de la réponse sans nécessiter de modification du modèle.",
    },
    {
      id: "gcp-genai-q09",
      domainId: "offre-google-cloud",
      difficulty: "facile",
      question: "Quel est le rôle principal de Vertex AI dans l'offre Google Cloud ?",
      options: [
        "C'est un outil de visualisation de données uniquement",
        "C'est la plateforme unifiée pour entraîner, adapter, déployer et gouverner des modèles de machine learning et d'IA générative",
        "C'est un service de stockage de fichiers exclusivement",
        "C'est un langage de programmation propriétaire de Google",
      ],
      correctIndex: 1,
      explanation: "Vertex AI est la plateforme unifiée de Google Cloud couvrant l'ensemble du cycle de vie des projets de machine learning et d'IA générative.",
    },
    {
      id: "gcp-genai-q10",
      domainId: "offre-google-cloud",
      difficulty: "moyen",
      question: "Une équipe veut comparer plusieurs modèles, dont des modèles open source, avant de choisir celui à utiliser pour un projet. Quel élément de Vertex AI répond à ce besoin ?",
      options: [
        "Model Garden",
        "Cloud Storage",
        "BigQuery",
        "Vertex AI Search",
      ],
      correctIndex: 0,
      explanation: "Model Garden est le catalogue de modèles de Vertex AI, regroupant les modèles Google, des modèles partenaires et des modèles open source pour permettre la comparaison.",
    },
    {
      id: "gcp-genai-q11",
      domainId: "offre-google-cloud",
      difficulty: "facile",
      question: "Comment se nomme la famille de modèles de fondation multimodaux développée par Google ?",
      options: [
        "Imagen",
        "Gemini",
        "BigQuery ML",
        "Model Garden",
      ],
      correctIndex: 1,
      explanation: "Gemini est la famille de modèles de fondation multimodaux de Google, déclinée en plusieurs tailles selon les besoins.",
    },
    {
      id: "gcp-genai-q12",
      domainId: "offre-google-cloud",
      difficulty: "moyen",
      question: "Pourquoi Gemini est-il décliné en plusieurs tailles de modèles plutôt que proposé sous une seule version ?",
      options: [
        "Pour ajuster le coût et la latence d'inférence à la complexité réelle de chaque tâche",
        "Parce que la loi l'exige dans certains pays",
        "Parce qu'un seul modèle ne peut techniquement pas traiter plusieurs langues",
        "Pour limiter l'accès du modèle aux seuls clients premium",
      ],
      correctIndex: 0,
      explanation: "Les différentes tailles de Gemini permettent d'adapter le coût et la vitesse d'inférence à la complexité de la tâche, plutôt que d'utiliser systématiquement le modèle le plus puissant et le plus coûteux.",
    },
    {
      id: "gcp-genai-q13",
      domainId: "offre-google-cloud",
      difficulty: "facile",
      question: "Quel service Google Cloud est spécialisé dans la génération et l'édition d'images à partir de texte ?",
      options: [
        "Imagen",
        "Gemini",
        "Vertex AI Search",
        "Model Garden",
      ],
      correctIndex: 0,
      explanation: "Imagen est le modèle Google Cloud dédié à la génération et à l'édition d'images à partir d'instructions textuelles.",
    },
    {
      id: "gcp-genai-q14",
      domainId: "offre-google-cloud",
      difficulty: "moyen",
      question: "Une entreprise veut permettre à ses employés de poser des questions en langage naturel sur ses manuels internes, sans réentraîner de modèle. Quel service Google Cloud correspond le mieux à ce besoin ?",
      options: [
        "Imagen",
        "Vertex AI Search",
        "Cloud Functions",
        "Model Garden seul, sans autre configuration",
      ],
      correctIndex: 1,
      explanation: "Vertex AI Search permet de créer des expériences de recherche et de question-réponse ancrées dans les documents propres à une entreprise, sans réentraînement du modèle.",
    },
    {
      id: "gcp-genai-q15",
      domainId: "offre-google-cloud",
      difficulty: "difficile",
      question: "Une organisation veut automatiser le traitement complet d'une demande client sur plusieurs étapes : lecture du message, consultation d'une base de commandes, puis rédaction d'une réponse. Quelle approche décrite dans l'offre Google Cloud correspond le mieux ?",
      options: [
        "Un simple appel de prompt unique sans outil externe",
        "La construction d'un agent combinant un modèle, des outils externes et une logique de décision",
        "L'achat d'un nouveau modèle de fondation entraîné spécifiquement pour cette entreprise",
        "L'utilisation d'Imagen seul",
      ],
      correctIndex: 1,
      explanation: "Un agent combine un modèle génératif, des outils externes (comme une base de commandes) et une logique de décision pour automatiser une tâche à plusieurs étapes.",
    },
    {
      id: "gcp-genai-q16",
      domainId: "offre-google-cloud",
      difficulty: "moyen",
      question: "Quel avantage principal apporte une plateforme unifiée comme Vertex AI à une organisation qui mène plusieurs projets d'IA en parallèle ?",
      options: [
        "Elle impose l'usage exclusif de modèles open source",
        "Elle réduit la fragmentation des outils et harmonise les standards de sécurité et de gouvernance entre les équipes",
        "Elle rend le fine-tuning obligatoire pour chaque projet",
        "Elle supprime le besoin de définir un cas d'usage métier",
      ],
      correctIndex: 1,
      explanation: "Une plateforme unifiée comme Vertex AI limite la fragmentation des outils entre équipes et garantit des standards communs de sécurité et de gouvernance sur l'ensemble des projets d'IA.",
    },
    {
      id: "gcp-genai-q17",
      domainId: "offre-google-cloud",
      difficulty: "facile",
      question: "Model Garden regroupe quels types de modèles ?",
      options: [
        "Uniquement des modèles développés par Google",
        "Des modèles de Google, des modèles de partenaires et des modèles open source",
        "Uniquement des modèles open source",
        "Uniquement des modèles spécialisés dans la génération d'images",
      ],
      correctIndex: 1,
      explanation: "Model Garden regroupe des modèles de fondation de Google, de partenaires et open source, accessibles depuis une interface unique dans Vertex AI.",
    },
    {
      id: "gcp-genai-q18",
      domainId: "offre-google-cloud",
      difficulty: "difficile",
      question: "Une équipe marketing veut générer des variantes visuelles d'une campagne tout en respectant des garde-fous contre les contenus problématiques. Quel élément de l'offre Google Cloud répond directement à cette double exigence de génération et de garde-fous intégrés ?",
      options: [
        "Vertex AI Search seul",
        "Imagen, qui intègre des garde-fous limitant la génération de contenus problématiques",
        "BigQuery",
        "Un agent construit sans aucun modèle génératif",
      ],
      correctIndex: 1,
      explanation: "Imagen génère et édite des images à partir de texte tout en intégrant des garde-fous destinés à limiter la génération de contenus problématiques, comme des images de personnes réelles sans consentement.",
    },
    {
      id: "gcp-genai-q19",
      domainId: "techniques-amelioration",
      difficulty: "facile",
      question: "Quelle est la technique la plus rapide et la moins coûteuse pour améliorer la réponse d'un modèle ?",
      options: [
        "Le fine-tuning",
        "Le prompt engineering",
        "L'entraînement d'un nouveau modèle de fondation",
        "Le RAG",
      ],
      correctIndex: 1,
      explanation: "Le prompt engineering ne modifie ni le modèle ni les données externes : c'est la technique la plus rapide et la moins coûteuse à mettre en œuvre.",
    },
    {
      id: "gcp-genai-q20",
      domainId: "techniques-amelioration",
      difficulty: "moyen",
      question: "Une entreprise veut que son assistant réponde en citant des passages précis issus de ses contrats internes, sans réentraîner de modèle. Quelle architecture correspond à ce besoin ?",
      options: [
        "Le fine-tuning uniquement",
        "Le RAG (retrieval-augmented generation)",
        "L'entraînement d'un modèle de fondation depuis zéro",
        "Le prompt engineering seul, sans aucune donnée externe",
      ],
      correctIndex: 1,
      explanation: "Le RAG recherche les passages pertinents dans une base documentaire et les transmet au modèle comme contexte, ce qui permet de citer des sources précises sans réentraîner le modèle.",
    },
    {
      id: "gcp-genai-q21",
      domainId: "techniques-amelioration",
      difficulty: "difficile",
      question: "Un modèle doit produire, à très grande échelle, des réponses dans un style rédactionnel très spécifique et constant, propre à l'entreprise. Le prompt engineering et le RAG n'y parviennent pas de façon satisfaisante. Quelle technique reste à envisager ?",
      options: [
        "Le grounding seul",
        "Le fine-tuning",
        "L'augmentation de la taille du prompt uniquement",
        "Le changement de fournisseur cloud",
      ],
      correctIndex: 1,
      explanation: "Le fine-tuning ajuste les paramètres internes du modèle à partir d'exemples spécifiques, ce qui convient quand un style très particulier doit être reproduit de façon constante à grande échelle.",
    },
    {
      id: "gcp-genai-q22",
      domainId: "techniques-amelioration",
      difficulty: "facile",
      question: "Qu'est-ce que le grounding (ancrage) d'un modèle d'IA générative ?",
      options: [
        "La suppression complète des réponses du modèle",
        "La connexion des réponses du modèle à des sources d'information vérifiables",
        "Le passage du modèle en mode hors ligne",
        "Le remplacement du modèle par une base de données classique",
      ],
      correctIndex: 1,
      explanation: "Le grounding connecte les réponses du modèle à des sources vérifiables, comme la recherche Google ou des documents d'entreprise, pour réduire les hallucinations.",
    },
    {
      id: "gcp-genai-q23",
      domainId: "techniques-amelioration",
      difficulty: "moyen",
      question: "Quel est le principal compromis à accepter lorsqu'une organisation choisit le fine-tuning plutôt que le prompt engineering ?",
      options: [
        "Un coût et un effort de mise en œuvre plus élevés, avec un besoin de données étiquetées et de réévaluation à chaque nouvelle version du modèle",
        "Aucune différence de coût ni d'effort",
        "Le fine-tuning est toujours moins cher que le prompt engineering",
        "Le fine-tuning élimine totalement le besoin de tester les réponses du modèle",
      ],
      correctIndex: 0,
      explanation: "Le fine-tuning exige davantage de données, de calcul et d'expertise que le prompt engineering, et doit être réévalué à chaque mise à jour du modèle de base.",
    },
    {
      id: "gcp-genai-q24",
      domainId: "techniques-amelioration",
      difficulty: "facile",
      question: "Le few-shot prompting consiste à faire quoi dans un prompt ?",
      options: [
        "Fournir quelques exemples de réponses attendues pour guider le modèle",
        "Réduire le prompt à un seul mot",
        "Supprimer tout contexte du prompt",
        "Envoyer le prompt plusieurs fois d'affilée sans le modifier",
      ],
      correctIndex: 0,
      explanation: "Le few-shot prompting fournit quelques exemples de réponses correctes directement dans le prompt afin de guider le modèle vers le format ou le style attendu.",
    },
    {
      id: "gcp-genai-q25",
      domainId: "techniques-amelioration",
      difficulty: "difficile",
      question: "Une équipe combine prompt engineering, RAG et un léger fine-tuning sur son application d'IA générative. Quel principe cette combinaison illustre-t-elle le mieux ?",
      options: [
        "Ces techniques doivent obligatoirement être utilisées séparément et jamais ensemble",
        "Ces techniques peuvent se combiner, chacune répondant à un besoin distinct : formulation, ancrage documentaire, calibrage du style",
        "Le fine-tuning rend le prompt engineering totalement inutile",
        "Le RAG remplace systématiquement le besoin de prompt engineering",
      ],
      correctIndex: 1,
      explanation: "Dans la pratique, ces techniques se combinent souvent : le prompt structure la demande, le RAG ancre la réponse dans des documents, et le fine-tuning calibre finement le style ou le ton.",
    },
    {
      id: "gcp-genai-q26",
      domainId: "techniques-amelioration",
      difficulty: "moyen",
      question: "Pourquoi le RAG limite-t-il les hallucinations par rapport à un modèle utilisé sans ancrage documentaire ?",
      options: [
        "Parce qu'il empêche complètement le modèle de générer du texte",
        "Parce que le modèle s'appuie sur des extraits de documents réels transmis en contexte plutôt que sur sa seule mémoire interne",
        "Parce qu'il supprime tout besoin de prompt",
        "Parce qu'il remplace le modèle par une simple recherche par mots-clés",
      ],
      correctIndex: 1,
      explanation: "Le RAG transmet au modèle des passages documentaires réels et pertinents comme contexte, ce qui réduit le risque qu'il invente une réponse à partir de sa seule mémoire interne.",
    },
    {
      id: "gcp-genai-q27",
      domainId: "strategie-business",
      difficulty: "facile",
      question: "Par quoi un projet d'IA générative réussi doit-il commencer selon les bonnes pratiques de cadrage ?",
      options: [
        "Le choix du modèle le plus puissant disponible",
        "L'identification d'un problème métier précis et d'une métrique de valeur claire",
        "L'achat immédiat de licences Vertex AI",
        "La rédaction du prompt final avant toute autre étape",
      ],
      correctIndex: 1,
      explanation: "Un projet d'IA générative se cadre d'abord par le problème métier à résoudre et une métrique claire de valeur, avant de choisir la technologie.",
    },
    {
      id: "gcp-genai-q28",
      domainId: "strategie-business",
      difficulty: "moyen",
      question: "Une équipe a validé un pilote d'IA générative rentable sur un faible volume de requêtes. Quel risque financier doit-elle anticiper avant un déploiement à grande échelle ?",
      options: [
        "Aucun, le coût reste identique quel que soit le volume",
        "Une hausse significative du coût récurrent d'inférence proportionnelle au volume de requêtes en production",
        "Une baisse automatique du coût à mesure que le volume augmente",
        "La disparition du besoin de calculer un retour sur investissement",
      ],
      correctIndex: 1,
      explanation: "Le coût d'inférence est récurrent et proportionnel au volume de requêtes. Un projet rentable en pilote peut voir son coût grimper fortement une fois déployé à l'échelle de toute l'organisation.",
    },
    {
      id: "gcp-genai-q29",
      domainId: "strategie-business",
      difficulty: "facile",
      question: "Que couvre la gouvernance d'un projet d'IA générative en entreprise ?",
      options: [
        "Uniquement le choix esthétique de l'interface utilisateur",
        "La qualité des données, la sécurité, les accès et la conformité réglementaire",
        "Uniquement le budget marketing du produit",
        "Uniquement la vitesse de réponse du modèle",
      ],
      correctIndex: 1,
      explanation: "La gouvernance d'un projet d'IA générative couvre la qualité et la provenance des données, la sécurité et la gestion des accès, ainsi que la conformité réglementaire applicable.",
    },
    {
      id: "gcp-genai-q30",
      domainId: "strategie-business",
      difficulty: "moyen",
      question: "Quels domaines d'application Google exclut-il explicitement de ses principes d'IA responsable ?",
      options: [
        "La traduction automatique et la synthèse de documents",
        "Les armes et la surveillance de masse portant atteinte aux normes internationalement acceptées",
        "La génération d'images publicitaires",
        "La recherche documentaire en entreprise",
      ],
      correctIndex: 1,
      explanation: "Les principes d'IA responsable de Google excluent explicitement certains usages, dont les armes et la surveillance de masse contraire aux normes internationalement acceptées.",
    },
    {
      id: "gcp-genai-q31",
      domainId: "strategie-business",
      difficulty: "facile",
      question: "Que signifie maintenir une supervision humaine, ou human in the loop, sur un système d'IA générative ?",
      options: [
        "Faire valider ou intervenir un humain sur les décisions à fort impact prises avec l'aide du système",
        "Remplacer entièrement l'humain par le modèle dès la mise en production",
        "Interdire toute utilisation du modèle en dehors des heures de bureau",
        "Limiter l'usage du modèle aux seuls tests internes, jamais en production",
      ],
      correctIndex: 0,
      explanation: "La supervision humaine consiste à maintenir une validation ou une intervention humaine sur les décisions à fort impact prises avec l'aide d'un système d'IA générative.",
    },
    {
      id: "gcp-genai-q32",
      domainId: "strategie-business",
      difficulty: "difficile",
      question: "Une organisation déploie un assistant d'IA générative en contact avec des clients externes, sans les informer qu'ils échangent avec une IA. Quel principe d'IA responsable cette pratique enfreint-elle le plus directement ?",
      options: [
        "Le principe de haute qualité scientifique",
        "Le principe de responsabilité envers les personnes concernées, qui implique une transparence sur la nature de l'interaction",
        "Le principe d'exclusion des armes",
        "Le principe de confidentialité des données uniquement",
      ],
      correctIndex: 1,
      explanation: "Ne pas informer les utilisateurs qu'ils interagissent avec une IA porte atteinte au principe de responsabilité et de transparence envers les personnes concernées, un pilier des principes d'IA responsable de Google.",
    },
    {
      id: "gcp-genai-q33",
      domainId: "strategie-business",
      difficulty: "moyen",
      question: "Pourquoi tester un modèle sur des cas limites et des populations diverses avant sa mise en production fait-il partie des bonnes pratiques d'IA responsable ?",
      options: [
        "Pour augmenter artificiellement le coût du projet",
        "Pour détecter d'éventuels biais avant qu'ils n'affectent des utilisateurs réels",
        "Parce que la loi l'interdit dans tous les pays",
        "Parce que cela remplace le besoin de toute supervision humaine ultérieure",
      ],
      correctIndex: 1,
      explanation: "Tester le modèle sur des cas limites et des populations diverses permet de détecter des biais avant la mise en production, plutôt que de les découvrir une fois le système déployé auprès des utilisateurs.",
    },
    {
      id: "gcp-genai-q34",
      domainId: "strategie-business",
      difficulty: "moyen",
      question: "Pourquoi un projet d'IA générative peut-il échouer même quand la technologie fonctionne correctement ?",
      options: [
        "Parce que le modèle choisi est toujours trop petit",
        "Par manque d'adhésion des équipes et des utilisateurs finaux, faute de conduite du changement adaptée",
        "Parce que Vertex AI ne permet pas de mesurer les performances",
        "Parce que les modèles Google ne supportent pas le français",
      ],
      correctIndex: 1,
      explanation: "Un projet peut échouer malgré une technologie fonctionnelle si les utilisateurs finaux n'y adhèrent pas, faute de compréhension de l'outil et de conduite du changement adaptée.",
    },
    {
      id: "gcp-genai-q35",
      domainId: "strategie-business",
      difficulty: "facile",
      question: "Quel est l'objectif principal des principes d'IA responsable publiés par Google ?",
      options: [
        "Maximiser uniquement la vitesse d'inférence des modèles",
        "Encadrer le développement et le déploiement de l'IA autour du bénéfice social, de la sécurité, de l'équité et de la responsabilité",
        "Imposer l'usage exclusif de modèles open source",
        "Réduire le nombre de modèles disponibles dans Model Garden",
      ],
      correctIndex: 1,
      explanation: "Les principes d'IA responsable de Google encadrent le développement et le déploiement de l'IA autour du bénéfice social, de la sécurité, de l'équité, de la confidentialité et de la responsabilité.",
    },
  ],
  studyPlan: [
    {
      label: "Jours 1-2 : bases de l'IA générative",
      detail: "Lire le module sur les fondamentaux (modèles de fondation, LLM, entraînement vs inférence, prompting) et apprendre les termes du glossaire liés à ce domaine.",
    },
    {
      label: "Jours 3-5 : découvrir l'offre Google Cloud",
      detail: "Étudier le module sur Vertex AI, Model Garden, Gemini, Imagen et les agents, puis refaire les questions du quiz sur ce domaine jusqu'à obtenir un score satisfaisant.",
    },
    {
      label: "Jours 6-8 : techniques d'amélioration des résultats",
      detail: "Travailler le module sur le prompt engineering, le grounding, le RAG et le fine-tuning, en s'entraînant à distinguer ces quatre techniques sur des cas concrets.",
    },
    {
      label: "Jours 9-11 : stratégie business et IA responsable",
      detail: "Lire le module sur le cadrage des projets, le ROI, la gouvernance et les principes d'IA responsable de Google, puis relire l'ensemble du glossaire.",
    },
    {
      label: "Jours 12-14 : révision finale et examens blancs",
      detail: "Refaire l'intégralité de la banque de questions dans le désordre, identifier les domaines les plus faibles et relire les sections correspondantes avant de passer l'examen.",
    },
  ],
};

export default certification;
