import type { Certification } from "@/content/types";

const certification: Certification = {
  slug: "gcp-generative-ai-leader",
  providerId: "gcp",
  code: "Generative AI Leader",
  name: "Google Cloud Generative AI Leader",
  level: "Fondamentaux",
  tagline: "The Google Cloud certification designed to lead generative AI initiatives without writing a single line of code.",
  description:
    "The Generative AI Leader certification validates an understanding of the concepts, tools, and business use cases of generative AI on Google Cloud. It targets decision-makers, product managers, consultants, and managers who need to scope generative AI projects without necessarily coding themselves. It serves as a common reference point between technical and non-technical teams on vocabulary, the capabilities of the Vertex AI platform, and responsible AI best practices.",
  officialUrl: "https://cloud.google.com/learn/certification/generative-ai-leader",
  format: {
    questionCount: 50,
    durationMinutes: 90,
    passingScore: "Not publicly disclosed by Google (pass/fail result only)",
    price: "Indicative price ~99 USD (check the current price on the Google Cloud site; the certification was free at launch)",
    deliveryMode: "Online exam with remote proctoring",
    isOfficialCertification: true,
  },
  domains: [
    {
      id: "fondamentaux",
      title: "Fundamentals of generative AI",
      weightPercent: 25,
      summary:
        "The basic concepts needed to understand what a foundation model is, how it is trained and used, and what sets generative AI apart from classic predictive AI.",
    },
    {
      id: "offre-google-cloud",
      title: "Google Cloud's generative AI offering",
      weightPercent: 30,
      summary:
        "The Vertex AI platform, Model Garden, the Gemini model family, Imagen, and the building blocks for constructing generative AI agents and applications.",
    },
    {
      id: "techniques-amelioration",
      title: "Techniques for improving model results",
      weightPercent: 25,
      summary:
        "The concrete levers for getting better responses from a model: prompt engineering, grounding, RAG, and fine-tuning.",
    },
    {
      id: "strategie-business",
      title: "Business strategy and responsible AI",
      weightPercent: 20,
      summary:
        "Scoping business use cases, evaluating return on investment, governing AI projects, and the responsible AI principles championed by Google.",
    },
  ],
  modules: [
    {
      slug: "comprendre-ia-generative",
      domainId: "fondamentaux",
      title: "Understanding generative AI and foundation models",
      readMinutes: 9,
      summary:
        "This module lays out the core vocabulary of generative AI: foundation models, large language models, training, inference, and prompting, giving a decision-maker the reference points needed before diving into the Google Cloud offering.",
      keyPoints: [
        "Generative AI produces new content (text, image, audio, code) rather than simply classifying or predicting a value.",
        "A foundation model is trained on very large volumes of data and then adapted to many different tasks.",
        "Training and inference are two distinct phases: the first shapes the model, the second uses it to produce a response.",
        "A prompt is the instruction sent to the model; its quality directly influences the quality of the response.",
        "Large language models (LLMs) are a special case of foundation model specialized in text and language.",
      ],
      sections: [
        {
          heading: "From predictive AI to generative AI",
          body: "Classic predictive AI learns to recognize patterns in existing data in order to classify, score, or forecast: detecting fraud, predicting churn, recommending a product already in a catalog. Generative AI goes further: it learns the deep structure of language, images, or sound in order to produce brand-new content. A text-generation model does not pick a response from a closed list; it constructs a new sequence of words that is coherent with the given context. This distinction is central for a decision-maker, because it changes the nature of the possible use cases: writing, summarization, code generation, visual creation, conversational dialogue, whereas predictive AI remains confined to classification or scoring tasks.",
        },
        {
          heading: "Foundation models",
          body: "A foundation model is a model trained on a very large volume of diverse data (text, code, and images depending on the case), with enough parameters to capture general regularities in language and reasoning. Its strength is versatility: the same base model can then be adapted, through prompting or fine-tuning, to a wide variety of tasks such as document summarization, code generation, or sentiment classification, without needing to train a dedicated model for each task. Large language models (LLMs) are the best-known family of foundation models, specialized in understanding and generating text. Google offers its own family of foundation models under the name Gemini, multimodal by design from the outset.",
        },
        {
          heading: "Training and inference",
          body: "Two distinct phases structure a model's lifecycle. Training consists of exposing the model to immense volumes of data to adjust its internal parameters, a computationally expensive process that runs once, or periodically for model updates. Inference is the use of an already-trained model to produce a response from a new input: this is what happens every time a user sends a prompt and receives a response. For a decision-maker, this distinction clarifies the cost structure: training a foundation model from scratch is reserved for a handful of players with massive infrastructure, whereas inference is accessible to any organization through an API such as Vertex AI's.",
        },
        {
          heading: "Prompting as the first lever",
          body: "The prompt is the text, or multimodal, instruction sent to the model to obtain a response. Without changing a single parameter of the model, how the prompt is worded strongly influences the quality, accuracy, and format of the response obtained. It is the fastest and least expensive lever for improving a result, before considering more advanced techniques such as RAG or fine-tuning, covered in another module. A good prompt specifies the context, the role expected of the model, the desired output format, and, if needed, examples of correct responses.",
        },
        {
          heading: "Multimodality and current limitations",
          body: "Recent models such as Gemini are multimodal: they process and generate several types of content (text, image, audio, video, code) within a single model. This opens up use cases that combine multiple formats, for example analyzing an image and answering a text question about it. These models nevertheless remain subject to known limitations: they can produce incorrect responses with confidence, a phenomenon called hallucination, and their knowledge is bounded by their training data as of a given date. These limitations are what justify the grounding and verification techniques presented later in the course.",
        },
      ],
    },
    {
      slug: "vertex-ai-et-offre-google-cloud",
      domainId: "offre-google-cloud",
      title: "Vertex AI, Model Garden, Gemini, and Imagen",
      readMinutes: 11,
      summary:
        "This module presents the Google Cloud generative AI ecosystem: the unified Vertex AI platform, the Model Garden catalog, the Gemini model family, the Imagen image generator, and the building blocks for constructing agents.",
      keyPoints: [
        "Vertex AI is Google Cloud's unified platform for training, adapting, deploying, and governing machine learning and generative AI models.",
        "Model Garden brings together foundation models from Google, partners, and open source, accessible from a single interface.",
        "Gemini is Google's family of multimodal models, available in several sizes depending on the desired cost/performance trade-off.",
        "Imagen is Google Cloud's model specialized in generating and editing images from text.",
        "Vertex AI Search and agent frameworks make it possible to build search applications and agents grounded in enterprise data.",
      ],
      sections: [
        {
          heading: "Vertex AI, the unified platform",
          body: "Vertex AI is Google Cloud's machine learning and generative AI platform. It centralizes the entire lifecycle of an AI project: access to models, adaptation through prompting or fine-tuning, evaluation, production deployment, and monitoring. For an organization, the value of a unified platform is that it reduces tool fragmentation between data science teams, product teams, and operations teams, and lets everyone benefit from the same security and governance standards across all AI projects. Vertex AI builds on existing Google Cloud infrastructure, which makes it easier to integrate with data already stored in BigQuery, Cloud Storage, or other cloud services.",
        },
        {
          heading: "Model Garden, the model catalog",
          body: "Model Garden is the catalog of models available in Vertex AI. It brings together Google's proprietary models such as Gemini and Imagen, partner models, and popular open source models. This catalog lets an organization compare several models on the same use case, choose the one offering the best trade-off between cost, latency, and response quality, and avoid depending on a single model provider. For a decision-maker, Model Garden embodies an important principle: choosing a model is a product decision, not just a technical one, and it must take budget, data sensitivity, and performance requirements into account.",
        },
        {
          heading: "The Gemini model family",
          body: "Gemini is the family of multimodal foundation models developed by Google. It comes in several variants addressing different needs: lighter, faster versions for simple tasks at large scale, and more powerful versions for complex reasoning or demanding multimodal tasks. This range makes it possible to match inference cost to the actual complexity of the task, rather than systematically using the most powerful and most expensive model. Gemini is accessible through Vertex AI, but also through other consumer-facing entry points, which makes it the foundation of Google's generative experiences, including its conversational assistant.",
        },
        {
          heading: "Imagen and image generation",
          body: "Imagen is Google Cloud's model dedicated to generating and editing images from text instructions. It can create original visuals, modify existing images, or extend their framing, with built-in safeguards to limit the generation of problematic content, such as images of real people without their consent. In an enterprise context, Imagen is typically used to speed up the production of marketing visuals, mockups, or creative variants, under human supervision before any publication.",
        },
        {
          heading: "Agents, Vertex AI Search, and enterprise applications",
          body: "Beyond raw models, Google Cloud offers building blocks for constructing complete applications. Vertex AI Search makes it possible to create search and question-answering experiences grounded in an enterprise's own documents, without having to retrain a model. Google Cloud's agent frameworks make it possible to assemble a model, external tools (API calls, databases, search engines), and a decision-making logic to automate multi-step tasks, for example handling a customer request end to end. These building blocks combine with Gemini and Model Garden to form complete generative AI applications, designed for professional use rather than isolated experimentation.",
        },
      ],
    },
    {
      slug: "ameliorer-resultats-modeles",
      domainId: "techniques-amelioration",
      title: "Prompt engineering, grounding, RAG, and fine-tuning",
      readMinutes: 10,
      summary:
        "This module details the four main techniques for improving the responses of a generative AI model, from the simplest and least expensive to the most demanding in terms of data and compute.",
      keyPoints: [
        "Prompt engineering optimizes the wording of the instruction without modifying the model or adding external data.",
        "Grounding anchors the model's responses in verifiable sources, such as Google Search or enterprise documents.",
        "RAG (retrieval-augmented generation) retrieves relevant information from a document base before generating the response.",
        "Fine-tuning adjusts the model's internal parameters based on examples specific to a domain or task.",
        "The choice of technique depends on the volume of data available, the budget, and the need for traceability of responses.",
      ],
      sections: [
        {
          heading: "Prompt engineering, the first reflex",
          body: "Prompt engineering consists of structuring and refining the instruction sent to the model to obtain a more accurate response, without touching the model itself. Common techniques include clearly defining a role or persona for the model, providing examples of expected responses, known as few-shot prompting, breaking a complex problem down into explicit steps, and specifying the desired output format. It is the fastest and least expensive technique to implement, which makes it the recommended starting point before considering heavier approaches such as RAG or fine-tuning.",
        },
        {
          heading: "Grounding, anchoring responses in facts",
          body: "Grounding consists of connecting the model's responses to verifiable sources of information rather than letting it generate a response based solely on its internal knowledge, which may be outdated or incorrect. On Google Cloud, grounding can rely on Google Search for public, up-to-date information, or on internal enterprise documents through Vertex AI Search. The main benefit of grounding is reducing hallucinations and making it possible to cite the sources used, a point that is often decisive in regulated contexts or those with strong reliability requirements.",
        },
        {
          heading: "RAG, retrieval-augmented generation",
          body: "RAG is an architecture that combines a document retrieval system with a generative model. Before responding, the system searches a document base (contracts, manuals, internal knowledge bases) for the passages most relevant to the question asked, then passes them to the model as context to construct its response. This approach makes it possible to leverage proprietary or very recent data without retraining the model, and it limits hallucinations since the model relies on real excerpts rather than on memory alone. RAG, however, requires setting up a search and indexing infrastructure, which represents a greater engineering effort than simple prompt engineering.",
        },
        {
          heading: "Fine-tuning, adapting the model itself",
          body: "Fine-tuning consists of continuing the training of a foundation model on a dataset specific to a task or domain, which modifies its internal parameters. This technique is suited to cases where a use case requires a very particular response style, specialized business vocabulary, or a task repeated at very large scale where a slight accuracy gain per request translates into substantial savings. Fine-tuning requires more labeled data, compute budget, and expertise than prompt engineering or RAG, and it must be re-evaluated with each new version of the base model. It is generally the last option considered, after exhausting the possible gains from prompting and RAG.",
        },
        {
          heading: "Choosing the right combination of techniques",
          body: "In practice, these techniques are not mutually exclusive: an enterprise application often combines a well-designed prompt, grounding on a document base via RAG, and sometimes light fine-tuning to calibrate the tone of responses. The choice depends on concrete criteria: the volume and freshness of available data, the budget allocated to the project, the need for traceability of responses, and the severity of possible errors. A decision-maker must be able to weigh these options with their technical team rather than imposing a solution up front, since complexity and cost rise sharply from simple prompting all the way to fine-tuning.",
        },
      ],
    },
    {
      slug: "strategie-ia-responsable",
      domainId: "strategie-business",
      title: "Scoping a generative AI project and responsible AI at Google",
      readMinutes: 9,
      summary:
        "This module covers identifying and evaluating business use cases, questions of return on investment and governance, and the responsible AI principles championed by Google.",
      keyPoints: [
        "A generative AI project is scoped first around the business problem to solve, not around the available technology.",
        "Evaluating return on investment must account for recurring inference costs, not just the initial setup cost.",
        "Governing a generative AI project covers data quality, security, access, and regulatory compliance.",
        "Google structures its responsible AI around public principles covering social benefit, safety, fairness, privacy, and human accountability.",
        "A responsible deployment includes bias testing, human oversight, and clear communication to end users about the use of AI.",
      ],
      sections: [
        {
          heading: "Starting from the use case, not the technology",
          body: "A successful generative AI project always starts from a precise business problem: reducing the time to handle a customer request, speeding up the drafting of internal documents, improving search within a knowledge base. A common mistake is choosing the technology before clarifying the problem, which leads to projects that are technically impressive but have no measurable business value. A decision-maker must be able to state the use case in terms of a clear business metric, such as time saved, satisfaction rate, or cost avoided, before asking technical teams to assess feasibility.",
        },
        {
          heading: "Evaluating return on investment",
          body: "Calculating the return on investment of a generative AI project differs from that of a classic software project. On top of initial development costs come recurring costs tied to inference, that is, the number of requests sent to the model in production, which vary with usage volume and the size of the chosen model. A project that looks profitable during a pilot phase with a small volume of requests can see its cost climb significantly once deployed across the entire organization. It is therefore essential to estimate the inference cost at the target scale as early as the scoping phase, and to compare several model sizes to find the best cost-performance trade-off for the targeted use case.",
        },
        {
          heading: "Governance and change management",
          body: "Governing a generative AI project covers several dimensions: the quality and provenance of the data used, particularly for RAG and fine-tuning, managing access and security around models and sensitive data, and compliance with regulations applicable to the industry. Beyond the technical aspect, change management is decisive: the teams involved must understand what the tool does, its limitations, and in which cases human validation remains necessary. A generative AI project without buy-in from end users often fails, even when the technology works correctly.",
        },
        {
          heading: "Google's responsible AI principles",
          body: "Google has published responsible AI principles that govern the development and deployment of its models. These principles require that an AI application be socially beneficial, avoid creating or reinforcing unfair bias, be built and tested for safety, be accountable to people, incorporate privacy design principles, uphold high standards of scientific excellence, and be made available for uses that accord with these principles, with certain application areas explicitly excluded, such as weapons or mass surveillance. For an organization using Vertex AI, these principles are not merely a statement of intent: they translate into concrete tools for bias evaluation, content filtering, and model documentation provided by Google Cloud.",
        },
        {
          heading: "Putting responsible AI into practice day to day",
          body: "In practice, a responsible generative AI deployment in an enterprise includes several practices: testing the model on edge cases and diverse populations to detect bias before going into production, maintaining human oversight over high-impact decisions rather than automating everything, clearly informing end users when they are interacting with generative AI rather than with a human, and setting up feedback mechanisms to correct errors identified after deployment. These practices do not slow a project down; they reduce the risk of having to pull it in an emergency after a reputational or regulatory incident.",
        },
      ],
    },
  ],
  glossary: [
    {
      term: "Foundation model",
      definition: "A model trained on a very large volume of diverse data, designed to be later adapted to many different tasks through prompting or fine-tuning.",
      domainId: "fondamentaux",
    },
    {
      term: "Large language model (LLM)",
      definition: "A foundation model specialized in understanding and generating text, trained on vast linguistic corpora.",
      domainId: "fondamentaux",
    },
    {
      term: "Inference",
      definition: "The phase of using an already-trained model to produce a response from a new input, as opposed to training.",
      domainId: "fondamentaux",
    },
    {
      term: "Training",
      definition: "The process by which a model adjusts its internal parameters based on large volumes of data, before it is put into service.",
      domainId: "fondamentaux",
    },
    {
      term: "Prompt",
      definition: "A text or multimodal instruction sent to a generative AI model to obtain a response.",
      domainId: "fondamentaux",
    },
    {
      term: "Hallucination",
      definition: "A response generated by a model that appears plausible and confident but is factually incorrect or made up.",
      domainId: "fondamentaux",
    },
    {
      term: "Multimodality",
      definition: "The ability of a model to process and generate several types of content simultaneously, such as text, images, audio, or video.",
      domainId: "fondamentaux",
    },
    {
      term: "Vertex AI",
      definition: "Google Cloud's unified platform for training, adapting, deploying, and governing machine learning and generative AI models.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Model Garden",
      definition: "The catalog of models available in Vertex AI, bringing together Google models, partner models, and open source models.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Gemini",
      definition: "Google's family of multimodal foundation models, available in several sizes depending on the desired cost-performance trade-off.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Imagen",
      definition: "Google Cloud's model dedicated to generating and editing images from text instructions.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Vertex AI Search",
      definition: "A Google Cloud service for creating search and question-answering experiences grounded in an enterprise's own documents.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Agent",
      definition: "A system combining a generative model, external tools, and a decision-making logic to autonomously automate a multi-step task.",
      domainId: "offre-google-cloud",
    },
    {
      term: "API",
      definition: "A programming interface that lets an application send requests to a model hosted on Vertex AI and receive its responses.",
      domainId: "offre-google-cloud",
    },
    {
      term: "Prompt engineering",
      definition: "The practice of wording and structuring a prompt so as to obtain the best possible response from a model, without modifying the model itself.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Few-shot prompting",
      definition: "A prompt engineering technique that consists of providing a few examples of expected responses within the prompt to guide the model.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Grounding",
      definition: "A technique for connecting a model's responses to verifiable sources of information, such as Google Search or enterprise documents, to reduce hallucinations.",
      domainId: "techniques-amelioration",
    },
    {
      term: "RAG (retrieval-augmented generation)",
      definition: "An architecture combining document retrieval with a generative model, where the most relevant passages from a document base are passed to the model as context before it responds.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Fine-tuning",
      definition: "Continuing the training of a foundation model on a dataset specific to a task or domain, which modifies its internal parameters.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Embedding",
      definition: "A numerical representation of text, an image, or other content in the form of a vector, used in particular for similarity search in a RAG system.",
      domainId: "techniques-amelioration",
    },
    {
      term: "Return on investment (ROI)",
      definition: "A measure of the value created by a generative AI project relative to its total cost, including recurring inference costs in production.",
      domainId: "strategie-business",
    },
    {
      term: "AI governance",
      definition: "The set of practices governing data quality, security, access, and regulatory compliance for a generative AI project.",
      domainId: "strategie-business",
    },
    {
      term: "Responsible AI",
      definition: "An approach to developing and deploying AI that aims to limit bias, protect privacy, ensure safety, and account for decisions made by a system.",
      domainId: "strategie-business",
    },
    {
      term: "Algorithmic bias",
      definition: "A systematic skew in a model's results that unfairly disadvantages certain groups or certain categories of data.",
      domainId: "strategie-business",
    },
    {
      term: "Human oversight (human in the loop)",
      definition: "The practice of maintaining human validation or intervention over high-impact decisions made with the help of a generative AI system.",
      domainId: "strategie-business",
    },
  ],
  quizBank: [
    {
      id: "gcp-genai-q01",
      domainId: "fondamentaux",
      difficulty: "facile",
      question: "What is the main difference between generative AI and classic predictive AI?",
      options: [
        "Generative AI produces new content, whereas predictive AI classifies or forecasts from existing categories",
        "Generative AI works only on structured numerical data",
        "Predictive AI is more recent than generative AI",
        "Generative AI needs no training data whatsoever",
      ],
      correctIndex: 0,
      explanation: "Generative AI creates brand-new content (text, image, code) while classic predictive AI classifies, scores, or forecasts based on categories or values that are already known.",
    },
    {
      id: "gcp-genai-q02",
      domainId: "fondamentaux",
      difficulty: "facile",
      question: "A product manager wants to understand why their technical team talks about two distinct phases, training and inference. What does inference represent?",
      options: [
        "The phase where the model adjusts its parameters on large volumes of data",
        "The phase of using an already-trained model to produce a response to a new request",
        "The phase of collecting data before any training",
        "The phase of retiring an obsolete model",
      ],
      correctIndex: 1,
      explanation: "Inference is the use of an already-trained model to respond to a new input. Training, on the other hand, adjusts the model's parameters based on data.",
    },
    {
      id: "gcp-genai-q03",
      domainId: "fondamentaux",
      difficulty: "moyen",
      question: "A team notices that a model confidently generates a factually wrong response on a specific topic. What is this phenomenon called?",
      options: [
        "An algorithmic bias",
        "A hallucination",
        "Overfitting",
        "A performance regression",
      ],
      correctIndex: 1,
      explanation: "A hallucination refers to a response generated by the model that appears plausible and confident but is actually incorrect or made up.",
    },
    {
      id: "gcp-genai-q04",
      domainId: "fondamentaux",
      difficulty: "moyen",
      question: "What is a foundation model?",
      options: [
        "A model trained for a single, very specific task, such as spam detection",
        "A model trained on vast, diverse data and designed to be adapted to many tasks",
        "A model that can only process text, never images",
        "An open source model as opposed to proprietary models",
      ],
      correctIndex: 1,
      explanation: "A foundation model is trained on large volumes of diverse data, which allows it to later be adapted to many tasks through prompting or fine-tuning.",
    },
    {
      id: "gcp-genai-q05",
      domainId: "fondamentaux",
      difficulty: "facile",
      question: "What is meant by the multimodality of a model like Gemini?",
      options: [
        "Its ability to run on several clouds at once",
        "Its ability to process and generate several types of content, such as text, image, and audio",
        "Its ability to be used by several users at the same time",
        "Its ability to automatically switch cloud providers",
      ],
      correctIndex: 1,
      explanation: "Multimodality refers to a model's ability to process and produce several types of content simultaneously: text, image, audio, video.",
    },
    {
      id: "gcp-genai-q06",
      domainId: "fondamentaux",
      difficulty: "difficile",
      question: "A startup wants to train its own foundation model from scratch for a customer service use case. What conclusion should a Generative AI Leader draw?",
      options: [
        "It is the best approach recommended by default for any generative AI project",
        "Training a foundation model from scratch requires considerable resources, whereas adapting an existing model through prompting, RAG, or fine-tuning is generally sufficient and far less costly",
        "It is technically impossible outside of Google",
        "It makes no difference in cost compared to using an existing model through an API",
      ],
      correctIndex: 1,
      explanation: "Training a foundation model from scratch requires considerable infrastructure and data volumes. The vast majority of enterprise use cases rely instead on adapting an existing model.",
    },
    {
      id: "gcp-genai-q07",
      domainId: "fondamentaux",
      difficulty: "moyen",
      question: "Why is an LLM (large language model) considered a special case of a foundation model?",
      options: [
        "Because it is always smaller than a foundation model",
        "Because it is a foundation model specialized in understanding and generating text",
        "Because it cannot be used through an API",
        "Because it is trained without any textual data",
      ],
      correctIndex: 1,
      explanation: "An LLM is a foundation model whose specialty is language: it is trained on vast textual corpora to understand and generate text.",
    },
    {
      id: "gcp-genai-q08",
      domainId: "fondamentaux",
      difficulty: "facile",
      question: "Which element directly influences the quality of a model's response without requiring any modification of the model itself?",
      options: [
        "Fine-tuning",
        "The prompt sent to the model",
        "Fully retraining the model",
        "Switching cloud providers",
      ],
      correctIndex: 1,
      explanation: "The prompt, that is, the instruction sent to the model, directly influences the quality of the response without requiring any modification of the model.",
    },
    {
      id: "gcp-genai-q09",
      domainId: "offre-google-cloud",
      difficulty: "facile",
      question: "What is the main role of Vertex AI in Google Cloud's offering?",
      options: [
        "It is a data visualization tool only",
        "It is the unified platform for training, adapting, deploying, and governing machine learning and generative AI models",
        "It is a file storage service exclusively",
        "It is a proprietary programming language from Google",
      ],
      correctIndex: 1,
      explanation: "Vertex AI is Google Cloud's unified platform covering the entire lifecycle of machine learning and generative AI projects.",
    },
    {
      id: "gcp-genai-q10",
      domainId: "offre-google-cloud",
      difficulty: "moyen",
      question: "A team wants to compare several models, including open source ones, before choosing which one to use for a project. Which element of Vertex AI meets this need?",
      options: [
        "Model Garden",
        "Cloud Storage",
        "BigQuery",
        "Vertex AI Search",
      ],
      correctIndex: 0,
      explanation: "Model Garden is Vertex AI's model catalog, bringing together Google models, partner models, and open source models to enable comparison.",
    },
    {
      id: "gcp-genai-q11",
      domainId: "offre-google-cloud",
      difficulty: "facile",
      question: "What is the name of the family of multimodal foundation models developed by Google?",
      options: [
        "Imagen",
        "Gemini",
        "BigQuery ML",
        "Model Garden",
      ],
      correctIndex: 1,
      explanation: "Gemini is Google's family of multimodal foundation models, available in several sizes depending on the need.",
    },
    {
      id: "gcp-genai-q12",
      domainId: "offre-google-cloud",
      difficulty: "moyen",
      question: "Why is Gemini offered in several model sizes rather than a single version?",
      options: [
        "To match inference cost and latency to the actual complexity of each task",
        "Because the law requires it in certain countries",
        "Because a single model technically cannot handle several languages",
        "To restrict model access to premium customers only",
      ],
      correctIndex: 0,
      explanation: "Gemini's different sizes make it possible to match inference cost and speed to the complexity of the task, rather than systematically using the most powerful and most expensive model.",
    },
    {
      id: "gcp-genai-q13",
      domainId: "offre-google-cloud",
      difficulty: "facile",
      question: "Which Google Cloud service is specialized in generating and editing images from text?",
      options: [
        "Imagen",
        "Gemini",
        "Vertex AI Search",
        "Model Garden",
      ],
      correctIndex: 0,
      explanation: "Imagen is Google Cloud's model dedicated to generating and editing images from text instructions.",
    },
    {
      id: "gcp-genai-q14",
      domainId: "offre-google-cloud",
      difficulty: "moyen",
      question: "A company wants to let its employees ask natural language questions about its internal manuals, without retraining a model. Which Google Cloud service best matches this need?",
      options: [
        "Imagen",
        "Vertex AI Search",
        "Cloud Functions",
        "Model Garden alone, with no other configuration",
      ],
      correctIndex: 1,
      explanation: "Vertex AI Search makes it possible to create search and question-answering experiences grounded in an enterprise's own documents, without retraining the model.",
    },
    {
      id: "gcp-genai-q15",
      domainId: "offre-google-cloud",
      difficulty: "difficile",
      question: "An organization wants to automate the full handling of a customer request across several steps: reading the message, checking an order database, then drafting a response. Which approach described in the Google Cloud offering best fits this?",
      options: [
        "A simple single prompt call with no external tool",
        "Building an agent combining a model, external tools, and a decision-making logic",
        "Buying a new foundation model trained specifically for this company",
        "Using Imagen alone",
      ],
      correctIndex: 1,
      explanation: "An agent combines a generative model, external tools (such as an order database), and a decision-making logic to automate a multi-step task.",
    },
    {
      id: "gcp-genai-q16",
      domainId: "offre-google-cloud",
      difficulty: "moyen",
      question: "What is the main advantage a unified platform like Vertex AI brings to an organization running several AI projects in parallel?",
      options: [
        "It requires exclusive use of open source models",
        "It reduces tool fragmentation and harmonizes security and governance standards across teams",
        "It makes fine-tuning mandatory for every project",
        "It removes the need to define a business use case",
      ],
      correctIndex: 1,
      explanation: "A unified platform like Vertex AI limits tool fragmentation between teams and guarantees common security and governance standards across all AI projects.",
    },
    {
      id: "gcp-genai-q17",
      domainId: "offre-google-cloud",
      difficulty: "facile",
      question: "What types of models does Model Garden bring together?",
      options: [
        "Only models developed by Google",
        "Models from Google, partner models, and open source models",
        "Only open source models",
        "Only models specialized in image generation",
      ],
      correctIndex: 1,
      explanation: "Model Garden brings together foundation models from Google, from partners, and open source ones, accessible from a single interface within Vertex AI.",
    },
    {
      id: "gcp-genai-q18",
      domainId: "offre-google-cloud",
      difficulty: "difficile",
      question: "A marketing team wants to generate visual variants for a campaign while respecting safeguards against problematic content. Which element of the Google Cloud offering directly meets this dual requirement of generation and built-in safeguards?",
      options: [
        "Vertex AI Search alone",
        "Imagen, which includes safeguards limiting the generation of problematic content",
        "BigQuery",
        "An agent built with no generative model at all",
      ],
      correctIndex: 1,
      explanation: "Imagen generates and edits images from text while including safeguards designed to limit the generation of problematic content, such as images of real people without their consent.",
    },
    {
      id: "gcp-genai-q19",
      domainId: "techniques-amelioration",
      difficulty: "facile",
      question: "What is the fastest and least expensive technique for improving a model's response?",
      options: [
        "Fine-tuning",
        "Prompt engineering",
        "Training a new foundation model",
        "RAG",
      ],
      correctIndex: 1,
      explanation: "Prompt engineering modifies neither the model nor any external data: it is the fastest and least expensive technique to implement.",
    },
    {
      id: "gcp-genai-q20",
      domainId: "techniques-amelioration",
      difficulty: "moyen",
      question: "A company wants its assistant to respond by citing specific passages from its internal contracts, without retraining a model. Which architecture fits this need?",
      options: [
        "Fine-tuning only",
        "RAG (retrieval-augmented generation)",
        "Training a foundation model from scratch",
        "Prompt engineering alone, with no external data",
      ],
      correctIndex: 1,
      explanation: "RAG retrieves the relevant passages from a document base and passes them to the model as context, which makes it possible to cite precise sources without retraining the model.",
    },
    {
      id: "gcp-genai-q21",
      domainId: "techniques-amelioration",
      difficulty: "difficile",
      question: "A model must produce, at very large scale, responses in a very specific and consistent writing style unique to the company. Prompt engineering and RAG do not achieve this satisfactorily. Which technique remains to be considered?",
      options: [
        "Grounding alone",
        "Fine-tuning",
        "Increasing the prompt size only",
        "Switching cloud providers",
      ],
      correctIndex: 1,
      explanation: "Fine-tuning adjusts the model's internal parameters based on specific examples, which suits cases where a very particular style must be reproduced consistently at large scale.",
    },
    {
      id: "gcp-genai-q22",
      domainId: "techniques-amelioration",
      difficulty: "facile",
      question: "What is grounding in a generative AI model?",
      options: [
        "The complete removal of the model's responses",
        "Connecting the model's responses to verifiable sources of information",
        "Putting the model into offline mode",
        "Replacing the model with a classic database",
      ],
      correctIndex: 1,
      explanation: "Grounding connects the model's responses to verifiable sources, such as Google Search or enterprise documents, to reduce hallucinations.",
    },
    {
      id: "gcp-genai-q23",
      domainId: "techniques-amelioration",
      difficulty: "moyen",
      question: "What is the main trade-off an organization accepts when choosing fine-tuning over prompt engineering?",
      options: [
        "Higher cost and implementation effort, along with a need for labeled data and re-evaluation with each new model version",
        "No difference in cost or effort",
        "Fine-tuning is always cheaper than prompt engineering",
        "Fine-tuning entirely eliminates the need to test the model's responses",
      ],
      correctIndex: 0,
      explanation: "Fine-tuning requires more data, compute, and expertise than prompt engineering, and it must be re-evaluated with each update of the base model.",
    },
    {
      id: "gcp-genai-q24",
      domainId: "techniques-amelioration",
      difficulty: "facile",
      question: "What does few-shot prompting involve doing in a prompt?",
      options: [
        "Providing a few examples of expected responses to guide the model",
        "Reducing the prompt to a single word",
        "Removing all context from the prompt",
        "Sending the prompt several times in a row without changing it",
      ],
      correctIndex: 0,
      explanation: "Few-shot prompting provides a few examples of correct responses directly in the prompt in order to guide the model toward the expected format or style.",
    },
    {
      id: "gcp-genai-q25",
      domainId: "techniques-amelioration",
      difficulty: "difficile",
      question: "A team combines prompt engineering, RAG, and light fine-tuning in its generative AI application. What principle does this combination best illustrate?",
      options: [
        "These techniques must always be used separately and never together",
        "These techniques can be combined, each addressing a distinct need: wording, document grounding, style calibration",
        "Fine-tuning makes prompt engineering completely unnecessary",
        "RAG systematically replaces the need for prompt engineering",
      ],
      correctIndex: 1,
      explanation: "In practice, these techniques are often combined: the prompt structures the request, RAG grounds the response in documents, and fine-tuning finely calibrates the style or tone.",
    },
    {
      id: "gcp-genai-q26",
      domainId: "techniques-amelioration",
      difficulty: "moyen",
      question: "Why does RAG reduce hallucinations compared to a model used without document grounding?",
      options: [
        "Because it completely prevents the model from generating text",
        "Because the model relies on excerpts from real documents passed in as context rather than on its internal memory alone",
        "Because it removes any need for a prompt",
        "Because it replaces the model with a simple keyword search",
      ],
      correctIndex: 1,
      explanation: "RAG passes real, relevant document passages to the model as context, which reduces the risk of the model making up a response based solely on its internal memory.",
    },
    {
      id: "gcp-genai-q27",
      domainId: "strategie-business",
      difficulty: "facile",
      question: "According to best scoping practices, what should a successful generative AI project start with?",
      options: [
        "Choosing the most powerful model available",
        "Identifying a precise business problem and a clear value metric",
        "Immediately purchasing Vertex AI licenses",
        "Writing the final prompt before any other step",
      ],
      correctIndex: 1,
      explanation: "A generative AI project is scoped first around the business problem to solve and a clear value metric, before choosing the technology.",
    },
    {
      id: "gcp-genai-q28",
      domainId: "strategie-business",
      difficulty: "moyen",
      question: "A team has validated a profitable generative AI pilot on a small volume of requests. What financial risk should it anticipate before deploying at large scale?",
      options: [
        "None, the cost stays the same regardless of volume",
        "A significant rise in the recurring inference cost, proportional to the volume of requests in production",
        "An automatic drop in cost as volume increases",
        "The disappearance of the need to calculate a return on investment",
      ],
      correctIndex: 1,
      explanation: "Inference cost is recurring and proportional to the volume of requests. A project that is profitable in a pilot can see its cost climb sharply once deployed across the entire organization.",
    },
    {
      id: "gcp-genai-q29",
      domainId: "strategie-business",
      difficulty: "facile",
      question: "What does the governance of a generative AI project in an enterprise cover?",
      options: [
        "Only the aesthetic choices of the user interface",
        "Data quality, security, access, and regulatory compliance",
        "Only the product's marketing budget",
        "Only the model's response speed",
      ],
      correctIndex: 1,
      explanation: "Governing a generative AI project covers the quality and provenance of data, security and access management, and applicable regulatory compliance.",
    },
    {
      id: "gcp-genai-q30",
      domainId: "strategie-business",
      difficulty: "moyen",
      question: "Which application areas does Google explicitly exclude from its responsible AI principles?",
      options: [
        "Machine translation and document summarization",
        "Weapons and mass surveillance that violate internationally accepted norms",
        "Generating advertising images",
        "Enterprise document search",
      ],
      correctIndex: 1,
      explanation: "Google's responsible AI principles explicitly exclude certain uses, including weapons and mass surveillance that violate internationally accepted norms.",
    },
    {
      id: "gcp-genai-q31",
      domainId: "strategie-business",
      difficulty: "facile",
      question: "What does maintaining human oversight, or human in the loop, over a generative AI system mean?",
      options: [
        "Having a human validate or intervene in high-impact decisions made with the help of the system",
        "Entirely replacing the human with the model as soon as it goes into production",
        "Banning any use of the model outside office hours",
        "Restricting the model's use to internal testing only, never in production",
      ],
      correctIndex: 0,
      explanation: "Human oversight consists of maintaining human validation or intervention over high-impact decisions made with the help of a generative AI system.",
    },
    {
      id: "gcp-genai-q32",
      domainId: "strategie-business",
      difficulty: "difficile",
      question: "An organization deploys a generative AI assistant that interacts with external customers, without informing them they are talking to an AI. Which responsible AI principle does this practice most directly violate?",
      options: [
        "The principle of high scientific standards",
        "The principle of accountability to people, which implies transparency about the nature of the interaction",
        "The principle excluding weapons",
        "The principle of data privacy alone",
      ],
      correctIndex: 1,
      explanation: "Not informing users that they are interacting with an AI undermines the principle of accountability and transparency toward the people affected, a cornerstone of Google's responsible AI principles.",
    },
    {
      id: "gcp-genai-q33",
      domainId: "strategie-business",
      difficulty: "moyen",
      question: "Why is testing a model on edge cases and diverse populations before production part of responsible AI best practices?",
      options: [
        "To artificially increase the project's cost",
        "To detect potential bias before it affects real users",
        "Because the law prohibits it in every country",
        "Because it replaces the need for any later human oversight",
      ],
      correctIndex: 1,
      explanation: "Testing the model on edge cases and diverse populations makes it possible to detect bias before going into production, rather than discovering it once the system is deployed to users.",
    },
    {
      id: "gcp-genai-q34",
      domainId: "strategie-business",
      difficulty: "moyen",
      question: "Why can a generative AI project fail even when the technology works correctly?",
      options: [
        "Because the chosen model is always too small",
        "Due to a lack of buy-in from teams and end users, for want of adequate change management",
        "Because Vertex AI cannot measure performance",
        "Because Google's models do not support French",
      ],
      correctIndex: 1,
      explanation: "A project can fail despite functioning technology if end users do not buy in, for lack of understanding of the tool and adequate change management.",
    },
    {
      id: "gcp-genai-q35",
      domainId: "strategie-business",
      difficulty: "facile",
      question: "What is the main goal of the responsible AI principles published by Google?",
      options: [
        "Maximizing only the inference speed of models",
        "Governing the development and deployment of AI around social benefit, safety, fairness, and accountability",
        "Requiring exclusive use of open source models",
        "Reducing the number of models available in Model Garden",
      ],
      correctIndex: 1,
      explanation: "Google's responsible AI principles govern the development and deployment of AI around social benefit, safety, fairness, privacy, and accountability.",
    },
  ],
  studyPlan: [
    {
      label: "Days 1-2: generative AI fundamentals",
      detail: "Read the module on the fundamentals (foundation models, LLMs, training vs. inference, prompting) and learn the glossary terms tied to this domain.",
    },
    {
      label: "Days 3-5: discover the Google Cloud offering",
      detail: "Study the module on Vertex AI, Model Garden, Gemini, Imagen, and agents, then retake the quiz questions on this domain until reaching a satisfactory score.",
    },
    {
      label: "Days 6-8: techniques for improving results",
      detail: "Work through the module on prompt engineering, grounding, RAG, and fine-tuning, practicing telling these four techniques apart on concrete cases.",
    },
    {
      label: "Days 9-11: business strategy and responsible AI",
      detail: "Read the module on project scoping, ROI, governance, and Google's responsible AI principles, then review the entire glossary.",
    },
    {
      label: "Days 12-14: final review and practice exams",
      detail: "Retake the entire question bank in random order, identify the weakest domains, and reread the corresponding sections before taking the exam.",
    },
  ],
};

export default certification;
